import { defineConfig } from "astro/config"
import icon from "astro-icon"
import sitemap from "@astrojs/sitemap"
import tailwind from "@astrojs/tailwind"
import { SITE_URL } from "./src/consts"

// https://astro.build/config
export default defineConfig({
	integrations: [
		icon({
			include: {
				mdi: [
					"arrow-right-thin",
					"close-circle",
					"email",
					"facebook",
					"filter-menu-outline",
					"instagram",
					"link-variant",
					"linkedin",
					"menu-down",
					"rss",
					"twitter",
					"youtube"
				]
			}
		}),
		tailwind({
			config: {
				applyBaseStyles: false
			}
		}),
		sitemap()
	],
	output: "hybrid",
	site: SITE_URL,
	redirects: {
		"/default-pdf-template-2": "/blog/pdf_template/default-pdf-template-2",
		"/default-pdf-template": "/blog/pdf_template/default-pdf-template",
		"/ile-kosztuje-plac-zabaw": "/blog/posts/ile-kosztuje-plac-zabaw",
		"/dotacje-dla-sektora-horeca-2024": "/blog/posts/dotacje-dla-sektora-horeca-2024",
		"/jakosc": "/blog/posts/jakosc",
		"/jak-dobrac-odpowiednie-wyposazenie-dla-placu-zabaw-dla-dzieci":
			"/blog/posts/jak-dobrac-odpowiednie-wyposazenie-dla-placu-zabaw-dla-dzieci",
		"/systemy-modulowe-poradnik": "/blog/posts/systemy-modulowe-poradnik",
		"/zabawa-i-nauka-ida-w-parze": "/blog/posts/zabawa-i-nauka-ida-w-parze",
		"/jak-korzystac-z-wybiegu-dla-psow-podstawowe-zasady":
			"/blog/posts/jak-korzystac-z-wybiegu-dla-psow-podstawowe-zasady",
		"/jak-wyglada-montaz-i-instalacja-wyposazenia-placu-zabaw":
			"/blog/posts/jak-wyglada-montaz-i-instalacja-wyposazenia-placu-zabaw",
		"/trening-agility-dla-psa-czyli-jak-rozwinac-sportowa-pasje-swojego-pupila":
			"/blog/posts/trening-agility-dla-psa-czyli-jak-rozwinac-sportowa-pasje-swojego-pupila",
		"/budzet-obywatelski-2016-z-comes-darmowy-poradnik":
			"/blog/posts/budzet-obywatelski-2016-z-comes-darmowy-poradnik",
		"/co-powinno-znalezc-sie-na-integracyjnym-placu-zabaw-a-czego-unikac":
			"/blog/posts/co-powinno-znalezc-sie-na-integracyjnym-placu-zabaw-a-czego-unikac",
		"/dofinansowanie-dla-przedszkoli-otrzymaj-dofinansowanie-na-urzadzenia-comes":
			"/blog/posts/dofinansowanie-dla-przedszkoli-otrzymaj-dofinansowanie-na-urzadzenia-comes",
		"/projekty-sredniego-placu-zabaw-wybierz-swoja-wersje":
			"/blog/posts/projekty-sredniego-placu-zabaw-wybierz-swoja-wersje",
		"/planowanie-krajobrazu-i-roslinnosc": "/blog/posts/planowanie-krajobrazu-i-roslinnosc",
		"/targi-place-zabaw-2014-2": "/blog/posts/targi-place-zabaw-2014-2",
		"/jakie-korzysci-plyna-z-obecnosci-wybiegu-dla-psow-w-naszym-otoczeniu":
			"/blog/posts/jakie-korzysci-plyna-z-obecnosci-wybiegu-dla-psow-w-naszym-otoczeniu",
		"/przeglad-placu-zabaw-na-co-zwrocic-uwage-po-okresie-zimowym":
			"/blog/posts/przeglad-placu-zabaw-na-co-zwrocic-uwage-po-okresie-zimowym",
		"/silownie-plenerowe-a-osoby-starsze": "/blog/posts/silownie-plenerowe-a-osoby-starsze",
		"/place-street-workout": "/blog/posts/place-street-workout",
		"/jak-zaprojektowac-swoj-wymarzony-plac-zabaw":
			"/blog/posts/jak-zaprojektowac-swoj-wymarzony-plac-zabaw",
		"/ogrodzenie-placu-zabaw": "/blog/posts/ogrodzenie-placu-zabaw",
		"/szkolenie-bezpieczenstwo-placow-zabaw-i-silowni-plenerowych":
			"/blog/posts/szkolenie-bezpieczenstwo-placow-zabaw-i-silowni-plenerowych",
		"/historie-o-piaskownicy": "/blog/posts/historie-o-piaskownicy",
		"/konsultacje-z-lokalna-spolecznoscia": "/blog/posts/konsultacje-z-lokalna-spolecznoscia",
		"/material-roslinny-na-place-zabaw-dla-dzieci":
			"/blog/posts/material-roslinny-na-place-zabaw-dla-dzieci",
		"/zabawa-w-zlobku": "/blog/posts/zabawa-w-zlobku",
		"/kwestia-kierownika-budowy-placu-zabaw": "/blog/posts/kwestia-kierownika-budowy-placu-zabaw",
		"/ostatni-dzwonek-dla-soltysow": "/blog/posts/ostatni-dzwonek-dla-soltysow",
		"/ruch-na-swiezym-powietrzu-zima": "/blog/posts/ruch-na-swiezym-powietrzu-zima",
		"/nawierzchnie-syntetyczne-dostepne-na-polskim-rynku":
			"/blog/posts/nawierzchnie-syntetyczne-dostepne-na-polskim-rynku",
		"/6-najczestszych-wypadkow-na-placu-zabaw":
			"/blog/posts/6-najczestszych-wypadkow-na-placu-zabaw",
		"/jak-rozmieszczac-urzadzenia-na-plac-zabaw":
			"/blog/posts/jak-rozmieszczac-urzadzenia-na-plac-zabaw",
		"/targi-place-zabaw-2014": "/blog/posts/targi-place-zabaw-2014",
		"/wejscie-na-plac-zabaw": "/blog/posts/wejscie-na-plac-zabaw",
		"/targi-aranzacji-przestrzeni-rekreacyjnej-dla-dzieci-i-doroslych-w-sosnowcu":
			"/blog/posts/targi-aranzacji-przestrzeni-rekreacyjnej-dla-dzieci-i-doroslych-w-sosnowcu",
		"/jakie-urzadzenia-komunalne-sa-niezbedne-na-placu-zabaw":
			"/blog/posts/jakie-urzadzenia-komunalne-sa-niezbedne-na-placu-zabaw",
		"/historia-placow-zabaw-cz-iii": "/blog/posts/historia-placow-zabaw-cz-iii",
		"/wandalizm-i-zagadnienia-bezpieczenstwa-na-placu-zabaw":
			"/blog/posts/wandalizm-i-zagadnienia-bezpieczenstwa-na-placu-zabaw",
		"/globalna-epidemia-braku-aktywnosci-fizycznej":
			"/blog/posts/globalna-epidemia-braku-aktywnosci-fizycznej",
		"/6-najczestszych-utrudnien-dla-niepelnosprawnych-na-placach-zabaw":
			"/blog/posts/6-najczestszych-utrudnien-dla-niepelnosprawnych-na-placach-zabaw",
		"/strefa-bezpieczenstwa-czym-jest-i-dlaczego-jest-tak-wazna":
			"/blog/posts/strefa-bezpieczenstwa-czym-jest-i-dlaczego-jest-tak-wazna",
		"/comes-na-targach-galabau-2014": "/blog/posts/comes-na-targach-galabau-2014",
		"/wybiegi-dla-psow-dlaczego-staja-sie-tak-popularne":
			"/blog/posts/wybiegi-dla-psow-dlaczego-staja-sie-tak-popularne",
		"/silownie-plenerowe-jak-korzystac-z-nich-prawidlowo":
			"/blog/posts/silownie-plenerowe-jak-korzystac-z-nich-prawidlowo",
		"/targi-kielce-green-city-expo-2018": "/blog/posts/targi-kielce-green-city-expo-2018",
		"/zasady-jakimi-powinnismy-sie-kierowac-podczas-wyboru-roslin-na-plac-zabaw":
			"/blog/posts/zasady-jakimi-powinnismy-sie-kierowac-podczas-wyboru-roslin-na-plac-zabaw",
		"/historia-placow-zabaw-dla-dzieci-cz-ii": "/blog/posts/historia-placow-zabaw-dla-dzieci-cz-ii",
		"/rodzice-i-opiekunowie-na-placu-zabaw": "/blog/posts/rodzice-i-opiekunowie-na-placu-zabaw",
		"/nagradzali-najlepszych-w-biznesie-wyroznili-tez-szydlowiecka-firme":
			"/blog/posts/nagradzali-najlepszych-w-biznesie-wyroznili-tez-szydlowiecka-firme",
		"/historia-placow-zabaw-cz-i": "/blog/posts/historia-placow-zabaw-cz-i",
		"/zestaw-06-51-234": "/blog/product/zestaw-06-51-234",
		"/kosz-kwadratowy-40l-z-tworzywa-hpl": "/blog/product/kosz-kwadratowy-40l-z-tworzywa-hpl",
		"/22231": "/blog/product/22231",
		"/drazki-potrojne": "/blog/product/drazki-potrojne",
		"/zestaw-06-44-01": "/blog/product/zestaw-06-44-01",
		"/kladka-3": "/blog/product/kladka-3",
		"/ogrodzenie-z-paneli-tematycznych": "/blog/product/ogrodzenie-z-paneli-tematycznych",
		"/ukladanka-pietnastka": "/blog/product/ukladanka-pietnastka",
		"/06-51-214": "/blog/product/06-51-214",
		"/zestaw-06-51-375": "/blog/product/zestaw-06-51-375",
		"/zestaw-06-59-136": "/blog/product/zestaw-06-59-136",
		"/kopiec": "/blog/product/kopiec",
		"/samochodzik": "/blog/product/samochodzik",
		"/obrecze-do-przeskokow-2": "/blog/product/obrecze-do-przeskokow-2",
		"/koordynator-ruchu": "/blog/product/koordynator-ruchu",
		"/helikopter": "/blog/product/helikopter",
		"/lawka-zwierzak-3": "/blog/product/lawka-zwierzak-3",
		"/poligon-czworokat": "/blog/product/poligon-czworokat",
		"/stopnie-po-luku": "/blog/product/stopnie-po-luku",
		"/zestaw-06-51-215": "/blog/product/zestaw-06-51-215",
		"/kosz-kwadratowy-40l-z-tworzywa-hpl-2": "/blog/product/kosz-kwadratowy-40l-z-tworzywa-hpl-2",
		"/piaskownica-gabi-2-x-3-m": "/blog/product/piaskownica-gabi-2-x-3-m",
		"/piaskownica-gabi-3-x-3-m": "/blog/product/piaskownica-gabi-3-x-3-m",
		"/domek-bolek": "/blog/product/domek-bolek",
		"/zestaw-06-43-01": "/blog/product/zestaw-06-43-01",
		"/regulowana-obrecz-do-przeskokow": "/blog/product/regulowana-obrecz-do-przeskokow",
		"/piaskownica-z-zadaszeniem": "/blog/product/piaskownica-z-zadaszeniem",
		"/kosz-kwadratowy-70l-z-tworzywa-hpl": "/blog/product/kosz-kwadratowy-70l-z-tworzywa-hpl",
		"/regulamin-placu-zabaw-3": "/blog/product/regulamin-placu-zabaw-3",
		"/zestaw-06-51-203": "/blog/product/zestaw-06-51-203",
		"/stojak-rowerowy-retro-2": "/blog/product/stojak-rowerowy-retro-2",
		"/stozek": "/blog/product/stozek",
		"/zestaw-dla-psow-3": "/blog/product/zestaw-dla-psow-3",
		"/podest-2": "/blog/product/podest-2",
		"/stopnie-2": "/blog/product/stopnie-2",
		"/zestaw-06-59-131": "/blog/product/zestaw-06-59-131",
		"/zestaw-06-59-134": "/blog/product/zestaw-06-59-134",
		"/zestaw-06-59-126": "/blog/product/zestaw-06-59-126",
		"/zestaw-statek-06-59-164": "/blog/product/zestaw-statek-06-59-164",
		"/plotek-regulowany-do-przeskokow-ii": "/blog/product/plotek-regulowany-do-przeskokow-ii",
		"/zestaw-modulowy-06-51-137": "/blog/product/zestaw-modulowy-06-51-137",
		"/zestaw-modulowy-06-51-135": "/blog/product/zestaw-modulowy-06-51-135",
		"/zestaw-modulowy-06-51-80": "/blog/product/zestaw-modulowy-06-51-80",
		"/zestaw-modulowy-06-51-148": "/blog/product/zestaw-modulowy-06-51-148",
		"/zestaw-modulowy-06-51-81": "/blog/product/zestaw-modulowy-06-51-81",
		"/zestaw-modulowy-06-51-79": "/blog/product/zestaw-modulowy-06-51-79",
		"/zestaw-modulowy-06-51-66": "/blog/product/zestaw-modulowy-06-51-66",
		"/zestaw-modulowy-06-51-58": "/blog/product/zestaw-modulowy-06-51-58",
		"/zestaw-modulowy-06-51-44": "/blog/product/zestaw-modulowy-06-51-44",
		"/zestaw-modulowy-06-51-29": "/blog/product/zestaw-modulowy-06-51-29",
		"/zestaw-modulowy-06-48-99": "/blog/product/zestaw-modulowy-06-48-99",
		"/zestaw-modulowy-06-48-85": "/blog/product/zestaw-modulowy-06-48-85",
		"/zestaw-modulowy-06-59-68": "/blog/product/zestaw-modulowy-06-59-68",
		"/zestaw-modulowy-06-59-78": "/blog/product/zestaw-modulowy-06-59-78",
		"/zestaw-modulowy-06-59-67": "/blog/product/zestaw-modulowy-06-59-67",
		"/zestaw-modulowy-06-59-65": "/blog/product/zestaw-modulowy-06-59-65",
		"/zestaw-modulowy-06-59-47": "/blog/product/zestaw-modulowy-06-59-47",
		"/zestaw-modulowy-06-59-41": "/blog/product/zestaw-modulowy-06-59-41",
		"/zestaw-modulowy-06-59-83": "/blog/product/zestaw-modulowy-06-59-83",
		"/zestaw-modulowy-06-59-82": "/blog/product/zestaw-modulowy-06-59-82",
		"/zestaw-modulowy-06-59-73": "/blog/product/zestaw-modulowy-06-59-73",
		"/zestaw-modulowy-06-59-70": "/blog/product/zestaw-modulowy-06-59-70",
		"/zestaw-modulowy-06-59-63": "/blog/product/zestaw-modulowy-06-59-63",
		"/zestaw-modulowy-06-59-46": "/blog/product/zestaw-modulowy-06-59-46",
		"/zestaw-modulowy-06-59-43": "/blog/product/zestaw-modulowy-06-59-43",
		"/zestaw-modulowy-06-59-24-2": "/blog/product/zestaw-modulowy-06-59-24-2",
		"/zestaw-modulowy-06-59-72": "/blog/product/zestaw-modulowy-06-59-72",
		"/zestaw-modulowy-06-59-69": "/blog/product/zestaw-modulowy-06-59-69",
		"/zestaw-modulowy-06-59-84": "/blog/product/zestaw-modulowy-06-59-84",
		"/zestaw-modulowy-06-59-76": "/blog/product/zestaw-modulowy-06-59-76",
		"/zestaw-modulowy-06-59-49": "/blog/product/zestaw-modulowy-06-59-49",
		"/zestaw-modulowy-06-59-61": "/blog/product/zestaw-modulowy-06-59-61",
		"/zestaw-modulowy-06-59-60": "/blog/product/zestaw-modulowy-06-59-60",
		"/zestaw-modulowy-06-59-58": "/blog/product/zestaw-modulowy-06-59-58",
		"/zestaw-modulowy-06-59-57": "/blog/product/zestaw-modulowy-06-59-57",
		"/zestaw-modulowy-06-59-56": "/blog/product/zestaw-modulowy-06-59-56",
		"/zestaw-modulowy-06-59-55": "/blog/product/zestaw-modulowy-06-59-55",
		"/zestaw-modulowy-06-59-44": "/blog/product/zestaw-modulowy-06-59-44",
		"/zestaw-modulowy-06-59-36": "/blog/product/zestaw-modulowy-06-59-36",
		"/zestaw-modulowy-06-51-121": "/blog/product/zestaw-modulowy-06-51-121",
		"/zestaw-modulowy-06-51-118": "/blog/product/zestaw-modulowy-06-51-118",
		"/zestaw-modulowy-06-51-104": "/blog/product/zestaw-modulowy-06-51-104",
		"/zestaw-modulowy-06-51-63": "/blog/product/zestaw-modulowy-06-51-63",
		"/zestaw-modulowy-06-51-99": "/blog/product/zestaw-modulowy-06-51-99",
		"/zestaw-modulowy-06-48-87": "/blog/product/zestaw-modulowy-06-48-87",
		"/zestaw-modulowy-06-51-94": "/blog/product/zestaw-modulowy-06-51-94",
		"/zestaw-modulowy-06-51-119": "/blog/product/zestaw-modulowy-06-51-119",
		"/zestaw-modulowy-06-51-74": "/blog/product/zestaw-modulowy-06-51-74",
		"/zestaw-modulowy-06-55-02": "/blog/product/zestaw-modulowy-06-55-02",
		"/zestaw-modulowy-06-53-02": "/blog/product/zestaw-modulowy-06-53-02",
		"/zestaw-modulowy-06-48-90": "/blog/product/zestaw-modulowy-06-48-90",
		"/zestaw-modulowy-06-51-182": "/blog/product/zestaw-modulowy-06-51-182",
		"/zestaw-modulowy-06-51-103": "/blog/product/zestaw-modulowy-06-51-103",
		"/zestaw-modulowy-06-51-109": "/blog/product/zestaw-modulowy-06-51-109",
		"/zestaw-modulowy-06-59-54": "/blog/product/zestaw-modulowy-06-59-54",
		"/zestaw-modulowy-06-59-79": "/blog/product/zestaw-modulowy-06-59-79",
		"/zestaw-modulowy-06-59-77": "/blog/product/zestaw-modulowy-06-59-77",
		"/zestaw-modulowy-06-59-48": "/blog/product/zestaw-modulowy-06-59-48",
		"/zestaw-modulowy-06-59-22": "/blog/product/zestaw-modulowy-06-59-22",
		"/zestaw-modulowy-06-51-136": "/blog/product/zestaw-modulowy-06-51-136",
		"/zestaw-modulowy-06-51-131": "/blog/product/zestaw-modulowy-06-51-131",
		"/zestaw-modulowy-06-51-130": "/blog/product/zestaw-modulowy-06-51-130",
		"/zestaw-modulowy-06-51-117": "/blog/product/zestaw-modulowy-06-51-117",
		"/zestaw-modulowy-06-51-83": "/blog/product/zestaw-modulowy-06-51-83",
		"/zestaw-modulowy-06-51-68": "/blog/product/zestaw-modulowy-06-51-68",
		"/zestaw-modulowy-06-51-30": "/blog/product/zestaw-modulowy-06-51-30",
		"/zestaw-modulowy-06-48-69": "/blog/product/zestaw-modulowy-06-48-69",
		"/pylon-3-stanowiskowy": "/blog/product/pylon-3-stanowiskowy",
		"/pylon-fitness": "/blog/product/pylon-fitness",
		"/slup-fitness": "/blog/product/slup-fitness",
		"/prasa-nozna": "/blog/product/prasa-nozna",
		"/cymbalki-na-plac-zabaw": "/blog/product/cymbalki-na-plac-zabaw",
		"/sciezka-zdrowia-zestaw-06-67-51": "/blog/product/sciezka-zdrowia-zestaw-06-67-51",
		"/sciezka-zdrowia-zestaw-06-57-55": "/blog/product/sciezka-zdrowia-zestaw-06-57-55",
		"/sciezka-zdrowia-zestaw-06-67-57": "/blog/product/sciezka-zdrowia-zestaw-06-67-57",
		"/sciezka-zdrowia-plotki-gimnastyczne": "/blog/product/sciezka-zdrowia-plotki-gimnastyczne",
		"/zestaw-gimnastyczny-fip-wzor-2010": "/blog/product/zestaw-gimnastyczny-fip-wzor-2010",
		"/zestaw-gimnastyczny-6-polowy-poligon-2":
			"/blog/product/zestaw-gimnastyczny-6-polowy-poligon-2",
		"/poligon-czworokat-max": "/blog/product/poligon-czworokat-max",
		"/zestaw-gimnastyczny-poligon-szesciokat-e":
			"/blog/product/zestaw-gimnastyczny-poligon-szesciokat-e",
		"/poligon-szesciokatny-z-siecia-z-lin": "/blog/product/poligon-szesciokatny-z-siecia-z-lin",
		"/sciezka-zdrowia-rownowaznia-waz": "/blog/product/sciezka-zdrowia-rownowaznia-waz",
		"/sciezka-zdrowia-skoczki-600-mm": "/blog/product/sciezka-zdrowia-skoczki-600-mm",
		"/skoczki-zoladz-lesna-polana": "/blog/product/skoczki-zoladz-lesna-polana",
		"/zjezdzalnia-dino-15-m": "/blog/product/zjezdzalnia-dino-15-m",
		"/zjezdzalnia-slon-b": "/blog/product/zjezdzalnia-slon-b",
		"/zjezdzalnia-slon-a": "/blog/product/zjezdzalnia-slon-a",
		"/zjezdzalnia-hipcio-i-plus": "/blog/product/zjezdzalnia-hipcio-i-plus",
		"/zjezdzalnia-krasnal-3-ciezarowka": "/blog/product/zjezdzalnia-krasnal-3-ciezarowka",
		"/zjezdzalnia-krasnal-3-dinozaur": "/blog/product/zjezdzalnia-krasnal-3-dinozaur",
		"/kiwak-trio": "/blog/product/kiwak-trio",
		"/przeplotnia-bartek": "/blog/product/przeplotnia-bartek",
		"/przeplotnia-kon": "/blog/product/przeplotnia-kon",
		"/przeplotnia-bajka-niedzwiadek": "/blog/product/przeplotnia-bajka-niedzwiadek",
		"/przeplotnia-bajka-tygrys": "/blog/product/przeplotnia-bajka-tygrys",
		"/przeplotnia-bajka-panda": "/blog/product/przeplotnia-bajka-panda",
		"/hustawka-sprezynowa-kolyska": "/blog/product/hustawka-sprezynowa-kolyska",
		"/hustawka-sprezynowa-rodeo-max-rybka": "/blog/product/hustawka-sprezynowa-rodeo-max-rybka",
		"/hustawka-sprezynowa-rodeo-max-delfinek":
			"/blog/product/hustawka-sprezynowa-rodeo-max-delfinek",
		"/hustawka-sprezynowa-rys-max-z-sowa": "/blog/product/hustawka-sprezynowa-rys-max-z-sowa",
		"/hustawka-sprezynowa-rys-b": "/blog/product/hustawka-sprezynowa-rys-b",
		"/hustawka-sprezynowa-lesna-polana": "/blog/product/hustawka-sprezynowa-lesna-polana",
		"/hustawka-sprezynowa-wodny-swiat": "/blog/product/hustawka-sprezynowa-wodny-swiat",
		"/hustawka-sprezynowa-orbita-kosmiczna": "/blog/product/hustawka-sprezynowa-orbita-kosmiczna",
		"/hustawka-sprezynowa-kareta-2": "/blog/product/hustawka-sprezynowa-kareta-2",
		"/hustawka-sprezynowa-autko-2": "/blog/product/hustawka-sprezynowa-autko-2",
		"/hustawka-sprezynowa-gruszka-2": "/blog/product/hustawka-sprezynowa-gruszka-2",
		"/hustawka-sprezynowa-gruszka-3": "/blog/product/hustawka-sprezynowa-gruszka-3",
		"/hustawka-sprezynowa-jeep-3": "/blog/product/hustawka-sprezynowa-jeep-3",
		"/hustawka-sprezynowa-autko-3": "/blog/product/hustawka-sprezynowa-autko-3",
		"/hustawka-sprezynowa-kulki": "/blog/product/hustawka-sprezynowa-kulki",
		"/hustawka-sprezynowa-zyrafa": "/blog/product/hustawka-sprezynowa-zyrafa",
		"/hustawka-sprezynowa-slonik": "/blog/product/hustawka-sprezynowa-slonik",
		"/hustawka-sprezynowa-piesek": "/blog/product/hustawka-sprezynowa-piesek",
		"/hustawka-sprezynowa-lew-2": "/blog/product/hustawka-sprezynowa-lew-2",
		"/hustawka-sprezynowa-krowka-2": "/blog/product/hustawka-sprezynowa-krowka-2",
		"/hustawka-sprezynowa-tygrysek": "/blog/product/hustawka-sprezynowa-tygrysek",
		"/hustawka-sprezynowa-motocykl": "/blog/product/hustawka-sprezynowa-motocykl",
		"/hustawka-sprezynowa-kotelek": "/blog/product/hustawka-sprezynowa-kotelek",
		"/hustawka-sprezynowa-konik": "/blog/product/hustawka-sprezynowa-konik",
		"/hustawka-sprezynowa-hipopotam": "/blog/product/hustawka-sprezynowa-hipopotam",
		"/hustawka-sprezynowa-owieczka": "/blog/product/hustawka-sprezynowa-owieczka",
		"/hustawka-sprezynowa-gruszka": "/blog/product/hustawka-sprezynowa-gruszka",
		"/hustawka-sprezynowa-jeep": "/blog/product/hustawka-sprezynowa-jeep",
		"/hustawka-sprezynowa-autko": "/blog/product/hustawka-sprezynowa-autko",
		"/hustawka-sprezynowa-klasyczna": "/blog/product/hustawka-sprezynowa-klasyczna",
		"/hustawka-sprezynowa-krowka": "/blog/product/hustawka-sprezynowa-krowka",
		"/karuzela-swing-2": "/blog/product/karuzela-swing-2",
		"/hustawka-jolka-4-aag": "/blog/product/hustawka-jolka-4-aag",
		"/hustawka-jolka-4-gg": "/blog/product/hustawka-jolka-4-gg",
		"/hustawka-kuba-mini-2": "/blog/product/hustawka-kuba-mini-2",
		"/hustawka-kasia": "/blog/product/hustawka-kasia",
		"/hustawka-tosia": "/blog/product/hustawka-tosia",
		"/street-workout-sthenos-5": "/blog/product/street-workout-sthenos-5",
		"/kolejka-linowa": "/blog/product/kolejka-linowa",
		"/zestaw-treningowy-baza-7": "/blog/product/zestaw-treningowy-baza-7",
		"/zestaw-treningowy-baza-6": "/blog/product/zestaw-treningowy-baza-6",
		"/zestaw-treningowy-baza-5": "/blog/product/zestaw-treningowy-baza-5",
		"/zestaw-treningowy-baza-4": "/blog/product/zestaw-treningowy-baza-4",
		"/zestaw-treningowy-baza-3": "/blog/product/zestaw-treningowy-baza-3",
		"/zestaw-treningowy-baza-2": "/blog/product/zestaw-treningowy-baza-2",
		"/zestaw-treningowy-baza-1": "/blog/product/zestaw-treningowy-baza-1",
		"/trenazer-rak-dla-niepelnosprawnych": "/blog/product/trenazer-rak-dla-niepelnosprawnych",
		"/motyl-sciskajaco-rozciagajacy-dla-niepelnosprawnych":
			"/blog/product/motyl-sciskajaco-rozciagajacy-dla-niepelnosprawnych",
		"/rowerek-reczny-dla-niepelnosprawnych": "/blog/product/rowerek-reczny-dla-niepelnosprawnych",
		"/kola-tai-chi-dla-niepelnosprawnych": "/blog/product/kola-tai-chi-dla-niepelnosprawnych",
		"/przyciskacz-nog-dla-niepelnosprawnych": "/blog/product/przyciskacz-nog-dla-niepelnosprawnych",
		"/rozruch-barkowy-dla-niepelnosprawnych": "/blog/product/rozruch-barkowy-dla-niepelnosprawnych",
		"/krzeslo-dla-niepelnosprawnych": "/blog/product/krzeslo-dla-niepelnosprawnych",
		"/wyciag-gorny-dla-niepelnosprawnych": "/blog/product/wyciag-gorny-dla-niepelnosprawnych",
		"/jezdziec-wolnostojacy": "/blog/product/jezdziec-wolnostojacy",
		"/orbitrek-wolnostojacy": "/blog/product/orbitrek-wolnostojacy",
		"/narciarz-wolnostojacy": "/blog/product/narciarz-wolnostojacy",
		"/kolarz-wolnostojacy": "/blog/product/kolarz-wolnostojacy",
		"/biegacz-wolnostojacy": "/blog/product/biegacz-wolnostojacy",
		"/wioslarz-wolnostojacy": "/blog/product/wioslarz-wolnostojacy",
		"/rowerek-wolnostojacy": "/blog/product/rowerek-wolnostojacy",
		"/rowerek-wolnostojacy-lawka": "/blog/product/rowerek-wolnostojacy-lawka",
		"/masazer-pionowy": "/blog/product/masazer-pionowy",
		"/masazer-poziomy": "/blog/product/masazer-poziomy",
		"/twister-siedzac": "/blog/product/twister-siedzac",
		"/sztanga": "/blog/product/sztanga",
		"/biegacz": "/blog/product/biegacz",
		"/pajacyk": "/blog/product/pajacyk",
		"/stepper": "/blog/product/stepper",
		"/prostownik-plecow": "/blog/product/prostownik-plecow",
		"/motyl-sciskajacy": "/blog/product/motyl-sciskajacy",
		"/motyl-rozciagajacy": "/blog/product/motyl-rozciagajacy",
		"/bieznia": "/blog/product/bieznia",
		"/jezdziec": "/blog/product/jezdziec",
		"/laweczka": "/blog/product/laweczka",
		"/wyciag-gorny": "/blog/product/wyciag-gorny",
		"/rowerek-reczny": "/blog/product/rowerek-reczny",
		"/narciarz": "/blog/product/narciarz",
		"/orbitrek": "/blog/product/orbitrek",
		"/prostownik-nog": "/blog/product/prostownik-nog",
		"/kolarz": "/blog/product/kolarz",
		"/rozruch-barkowy": "/blog/product/rozruch-barkowy",
		"/kola-tai-chi": "/blog/product/kola-tai-chi",
		"/twister": "/blog/product/twister",
		"/wioslarz": "/blog/product/wioslarz",
		"/wahadlo": "/blog/product/wahadlo",
		"/drabinka": "/blog/product/drabinka",
		"/podciag-nog": "/blog/product/podciag-nog",
		"/laweczka-skosna-z-uchwytami": "/blog/product/laweczka-skosna-z-uchwytami",
		"/laweczka-skosna": "/blog/product/laweczka-skosna",
		"/platforma-treningowa": "/blog/product/platforma-treningowa",
		"/drazek": "/blog/product/drazek",
		"/trener-nog": "/blog/product/trener-nog",
		"/tablica-informacyjna": "/blog/product/tablica-informacyjna",
		"/karuzela-talerzowa-bak-2": "/blog/product/karuzela-talerzowa-bak-2",
		"/stolik-z-lawkami-senior": "/blog/product/stolik-z-lawkami-senior",
		"/stolik-z-lawkami-dla-dzieci": "/blog/product/stolik-z-lawkami-dla-dzieci",
		"/podest-sthenos": "/blog/product/podest-sthenos",
		"/schody": "/blog/product/schody",
		"/platforma-600": "/blog/product/platforma-600",
		"/platforma-400": "/blog/product/platforma-400",
		"/scianka-pionowa": "/blog/product/scianka-pionowa",
		"/skrzynia-300x1300x450-mm": "/blog/product/skrzynia-300x1300x450-mm",
		"/skrzynia-1000x1000x900-mm": "/blog/product/skrzynia-1000x1000x900-mm",
		"/skrzynia-1000x1000x450-mm": "/blog/product/skrzynia-1000x1000x450-mm",
		"/skrzynia-1000x1000x1850-mm": "/blog/product/skrzynia-1000x1000x1850-mm",
		"/zestaw-modulowy-06-59-39": "/blog/product/zestaw-modulowy-06-59-39",
		"/zestaw-modulowy-06-59-38": "/blog/product/zestaw-modulowy-06-59-38",
		"/zestaw-modulowy-06-59-37": "/blog/product/zestaw-modulowy-06-59-37",
		"/zestaw-modulowy-06-59-29": "/blog/product/zestaw-modulowy-06-59-29",
		"/zestaw-modulowy-06-59-40": "/blog/product/zestaw-modulowy-06-59-40",
		"/zestaw-modulowy-06-59-33": "/blog/product/zestaw-modulowy-06-59-33",
		"/zestaw-modulowy-06-59-27": "/blog/product/zestaw-modulowy-06-59-27",
		"/zestaw-modulowy-06-59-23": "/blog/product/zestaw-modulowy-06-59-23",
		"/zestaw-modulowy-06-59-21": "/blog/product/zestaw-modulowy-06-59-21",
		"/zestaw-modulowy-06-59-30": "/blog/product/zestaw-modulowy-06-59-30",
		"/zestaw-modulowy-06-51-49": "/blog/product/zestaw-modulowy-06-51-49",
		"/zestaw-modulowy-06-51-34": "/blog/product/zestaw-modulowy-06-51-34",
		"/zestaw-modulowy-06-48-67": "/blog/product/zestaw-modulowy-06-48-67",
		"/zestaw-modulowy-06-48-86": "/blog/product/zestaw-modulowy-06-48-86",
		"/zestaw-modulowy-06-48-56": "/blog/product/zestaw-modulowy-06-48-56",
		"/zestaw-modulowy-06-51-07": "/blog/product/zestaw-modulowy-06-51-07",
		"/zestaw-modulowy-06-51-17": "/blog/product/zestaw-modulowy-06-51-17",
		"/zestaw-modulowy-06-48-97": "/blog/product/zestaw-modulowy-06-48-97",
		"/zestaw-modulowy-06-52-08-twierdza-dwie-baszty":
			"/blog/product/zestaw-modulowy-06-52-08-twierdza-dwie-baszty",
		"/zestaw-modulowy-06-46-03-pionier-super-max":
			"/blog/product/zestaw-modulowy-06-46-03-pionier-super-max",
		"/slup-niski": "/blog/product/slup-niski",
		"/tunel-dlugi-element-zestawu-sciezka-zdrowia":
			"/blog/product/tunel-dlugi-element-zestawu-sciezka-zdrowia",
		"/kladka-element-zestawu-sciezka-zdrowia":
			"/blog/product/kladka-element-zestawu-sciezka-zdrowia",
		"/poligon-czworokat-mini": "/blog/product/poligon-czworokat-mini",
		"/karuzela-beta": "/blog/product/karuzela-beta",
		"/karuzela-spodek": "/blog/product/karuzela-spodek",
		"/karuzela-pszczolka": "/blog/product/karuzela-pszczolka",
		"/karuzela-pszczola": "/blog/product/karuzela-pszczola",
		"/hustawka-sprezynowa-lew": "/blog/product/hustawka-sprezynowa-lew",
		"/hustawka-sprezynowa-dinozaur": "/blog/product/hustawka-sprezynowa-dinozaur",
		"/hustawka-sprezynowa-slon": "/blog/product/hustawka-sprezynowa-slon",
		"/hustawka-sprezynowa-rybka": "/blog/product/hustawka-sprezynowa-rybka",
		"/hustawka-sprezynowa-krolik": "/blog/product/hustawka-sprezynowa-krolik",
		"/zestaw-modulowy-06-59-32": "/blog/product/zestaw-modulowy-06-59-32",
		"/scianka-gimnastyczna": "/blog/product/scianka-gimnastyczna",
		"/scianka-linowa-pojedyncza": "/blog/product/scianka-linowa-pojedyncza",
		"/scianka-linowa-lukowa": "/blog/product/scianka-linowa-lukowa",
		"/scianka-linowa-prosta": "/blog/product/scianka-linowa-prosta",
		"/hustawka-sprezynowa-statek-kosmiczny": "/blog/product/hustawka-sprezynowa-statek-kosmiczny",
		"/domek-tomek-kosmiczny": "/blog/product/domek-tomek-kosmiczny",
		"/hustawka-sprezynowa-rakieta": "/blog/product/hustawka-sprezynowa-rakieta",
		"/zestaw-modulowy-06-59-13": "/blog/product/zestaw-modulowy-06-59-13",
		"/zestaw-modulowy-06-59-15": "/blog/product/zestaw-modulowy-06-59-15",
		"/zestaw-modulowy-06-48-84": "/blog/product/zestaw-modulowy-06-48-84",
		"/zestaw-modulowy-06-48-75": "/blog/product/zestaw-modulowy-06-48-75",
		"/zestaw-modulowy-06-48-13": "/blog/product/zestaw-modulowy-06-48-13",
		"/zestaw-modulowy-06-48-93": "/blog/product/zestaw-modulowy-06-48-93",
		"/zestaw-modulowy-06-48-48": "/blog/product/zestaw-modulowy-06-48-48",
		"/zestaw-modulowy-06-48-46": "/blog/product/zestaw-modulowy-06-48-46",
		"/zestaw-modulowy-06-48-70": "/blog/product/zestaw-modulowy-06-48-70",
		"/zestaw-modulowy-06-48-14": "/blog/product/zestaw-modulowy-06-48-14",
		"/zestaw-modulowy-06-48-31": "/blog/product/zestaw-modulowy-06-48-31",
		"/zestaw-modulowy-06-51-01": "/blog/product/zestaw-modulowy-06-51-01",
		"/zestaw-modulowy-06-48-17": "/blog/product/zestaw-modulowy-06-48-17",
		"/zestaw-modulowy-06-48-59": "/blog/product/zestaw-modulowy-06-48-59",
		"/rownowaznia": "/blog/product/rownowaznia",
		"/parking-dla-psow-2": "/blog/product/parking-dla-psow-2",
		"/parking-dla-psow-1": "/blog/product/parking-dla-psow-1",
		"/tunel-dla-psow": "/blog/product/tunel-dla-psow",
		"/podest": "/blog/product/podest",
		"/luk-do-przechodzenia": "/blog/product/luk-do-przechodzenia",
		"/plotek-do-przeskokow": "/blog/product/plotek-do-przeskokow",
		"/stopnie": "/blog/product/stopnie",
		"/hustawka-dla-psow": "/blog/product/hustawka-dla-psow",
		"/kladka-dla-psow": "/blog/product/kladka-dla-psow",
		"/trap-dla-psow": "/blog/product/trap-dla-psow",
		"/obrecz-do-przeskokow": "/blog/product/obrecz-do-przeskokow",
		"/obrecze-do-przeskokow": "/blog/product/obrecze-do-przeskokow",
		"/scianka-przejscie": "/blog/product/scianka-przejscie",
		"/piaskownica-malwinka-wodny-swiat": "/blog/product/piaskownica-malwinka-wodny-swiat",
		"/hustawka-sprezynowa-deska": "/blog/product/hustawka-sprezynowa-deska",
		"/hustawka-sprezynowa-zaglowka": "/blog/product/hustawka-sprezynowa-zaglowka",
		"/zestaw-modulowy-06-59-10": "/blog/product/zestaw-modulowy-06-59-10",
		"/hustawka-sprezynowa-delfin": "/blog/product/hustawka-sprezynowa-delfin",
		"/okret-hustawka-sprezynowa-comes": "/blog/product/okret-hustawka-sprezynowa-comes",
		"/zestaw-gimnastyczny-poligon-wodny-swiat":
			"/blog/product/zestaw-gimnastyczny-poligon-wodny-swiat",
		"/kosz-parkowy-okragly-na-jednej-nodze": "/blog/product/kosz-parkowy-okragly-na-jednej-nodze",
		"/trampolina-okragla": "/blog/product/trampolina-okragla",
		"/trampolina-kwadratowa-150x150": "/blog/product/trampolina-kwadratowa-150x150",
		"/trampolina-kwadratowa-200x200": "/blog/product/trampolina-kwadratowa-200x200",
		"/trampolina-kwadratowa-150x200": "/blog/product/trampolina-kwadratowa-150x200",
		"/stojak-rowerowy-retro": "/blog/product/stojak-rowerowy-retro",
		"/stojak-na-hulajnogi": "/blog/product/stojak-na-hulajnogi",
		"/stojak-rowerowy-modern-1": "/blog/product/stojak-rowerowy-modern-1",
		"/kosz-parkowy-kwadratowy": "/blog/product/kosz-parkowy-kwadratowy",
		"/dwie-sieci": "/blog/product/dwie-sieci",
		"/scianka-linowa-pionowa-element-zestawu-sciezka-zdrowia":
			"/blog/product/scianka-linowa-pionowa-element-zestawu-sciezka-zdrowia",
		"/scianka-guzowa-element-zestawu-sciezka-zdrowia":
			"/blog/product/scianka-guzowa-element-zestawu-sciezka-zdrowia",
		"/rownowaznia-na-sprezynach-2-element-zestawu-sciezka-zdrowia":
			"/blog/product/rownowaznia-na-sprezynach-2-element-zestawu-sciezka-zdrowia",
		"/siec-przestrzenna-2-element-zestawu-sciezka-zdrowia":
			"/blog/product/siec-przestrzenna-2-element-zestawu-sciezka-zdrowia",
		"/mostek-linowy-2-element-zestawu-sciezka-zdrowia":
			"/blog/product/mostek-linowy-2-element-zestawu-sciezka-zdrowia",
		"/siec-przestrzenna-1": "/blog/product/siec-przestrzenna-1",
		"/mostek-linowy-1-element-zestawu-sciezka-zdrowia":
			"/blog/product/mostek-linowy-1-element-zestawu-sciezka-zdrowia",
		"/podest-kwadratowy-element-zestawu-sciezka-zdrowia":
			"/blog/product/podest-kwadratowy-element-zestawu-sciezka-zdrowia",
		"/tunel-element-zestawu-sciezka-zdrowia": "/blog/product/tunel-element-zestawu-sciezka-zdrowia",
		"/podest-trojkatny-element-zestawu-sciezka-zdrowia":
			"/blog/product/podest-trojkatny-element-zestawu-sciezka-zdrowia",
		"/przeplotnia-linowa-pozioma-element-zestawu-sciezka-zdrowia":
			"/blog/product/przeplotnia-linowa-pozioma-element-zestawu-sciezka-zdrowia",
		"/lezak-plenerowy": "/blog/product/lezak-plenerowy",
		"/zestaw-rekreacyjny-jednowiezowy-julek-c":
			"/blog/product/zestaw-rekreacyjny-jednowiezowy-julek-c",
		"/platforma-wirujaca-piruet": "/blog/product/platforma-wirujaca-piruet",
		"/urzadzenie-ruchowe-surfer": "/blog/product/urzadzenie-ruchowe-surfer",
		"/hustawka-piotr-3": "/blog/product/hustawka-piotr-3",
		"/hustawka-zintegrowana-zula-b": "/blog/product/hustawka-zintegrowana-zula-b",
		"/hustawka-familijna": "/blog/product/hustawka-familijna",
		"/hustawka-zula-c": "/blog/product/hustawka-zula-c",
		"/hustawka-jolka-3": "/blog/product/hustawka-jolka-3",
		"/zestaw-rekreacyjny-lesna-polana": "/blog/product/zestaw-rekreacyjny-lesna-polana",
		"/regulamin-placu-zabaw-sowa": "/blog/product/regulamin-placu-zabaw-sowa",
		"/zjezdzalnia-niedzwiadek": "/blog/product/zjezdzalnia-niedzwiadek",
		"/skoczki-lesna-polana": "/blog/product/skoczki-lesna-polana",
		"/rakieta-trojstronna-lesna-polana": "/blog/product/rakieta-trojstronna-lesna-polana",
		"/hustawka-zula-lesna-polana": "/blog/product/hustawka-zula-lesna-polana",
		"/piaskownica-malwa-lesna-polana": "/blog/product/piaskownica-malwa-lesna-polana",
		"/zestaw-rekreacyjny-orbita-lesna-polana":
			"/blog/product/zestaw-rekreacyjny-orbita-lesna-polana",
		"/lawka-julia-lesna-polana": "/blog/product/lawka-julia-lesna-polana",
		"/karuzela-alfa-lesna-polana": "/blog/product/karuzela-alfa-lesna-polana",
		"/domek-tomek-lesna-polana": "/blog/product/domek-tomek-lesna-polana",
		"/hustawka-sprezynowa-bobr": "/blog/product/hustawka-sprezynowa-bobr",
		"/hustawka-sprezynowa-wiewiorka": "/blog/product/hustawka-sprezynowa-wiewiorka",
		"/hustawka-sprezynowa-slimak": "/blog/product/hustawka-sprezynowa-slimak",
		"/hustawka-sprezynowa-biedronka": "/blog/product/hustawka-sprezynowa-biedronka",
		"/hustawka-sprezynowa-sowa": "/blog/product/hustawka-sprezynowa-sowa",
		"/hustawka-sprezynowa-jez": "/blog/product/hustawka-sprezynowa-jez",
		"/hustawka-sprezynowa-zolw": "/blog/product/hustawka-sprezynowa-zolw",
		"/przeplotnia-bajka-lesna-polana": "/blog/product/przeplotnia-bajka-lesna-polana",
		"/tunel-integracyjny-lesna-polana": "/blog/product/tunel-integracyjny-lesna-polana",
		"/zestaw-rekreacyjny-zloty-stok-max-dziki-zachod":
			"/blog/product/zestaw-rekreacyjny-zloty-stok-max-dziki-zachod",
		"/zestaw-rekreacyjny-zloty-stok-b-dziki-zachod":
			"/blog/product/zestaw-rekreacyjny-zloty-stok-b-dziki-zachod",
		"/hustawka-sprezynowa-kareta": "/blog/product/hustawka-sprezynowa-kareta",
		"/lawka-julia": "/blog/product/lawka-julia",
		"/hustawka-sprezynowa-byczek": "/blog/product/hustawka-sprezynowa-byczek",
		"/zestaw-rekreacyjny-zloty-stok-a-dziki-zachod":
			"/blog/product/zestaw-rekreacyjny-zloty-stok-a-dziki-zachod",
		"/hustawka-sprezynowa-dylizans": "/blog/product/hustawka-sprezynowa-dylizans",
		"/zestaw-gimnastyczny-fip": "/blog/product/zestaw-gimnastyczny-fip",
		"/tunel-integracyjny": "/blog/product/tunel-integracyjny",
		"/mostek-lancuchowy-element-zestawu-sciezka-zdrowia":
			"/blog/product/mostek-lancuchowy-element-zestawu-sciezka-zdrowia",
		"/skoczki-element-zestawu-sciezka-zdrowia":
			"/blog/product/skoczki-element-zestawu-sciezka-zdrowia",
		"/drazki-gimnastyczne-element-zestawu-sciezka-zdrowia":
			"/blog/product/drazki-gimnastyczne-element-zestawu-sciezka-zdrowia",
		"/zestaw-rekreacyjny-smiglak-3": "/blog/product/zestaw-rekreacyjny-smiglak-3",
		"/zestaw-rekreacyjny-smiglak-2": "/blog/product/zestaw-rekreacyjny-smiglak-2",
		"/zestaw-rekreacyjny-jednowiezowy-smiglak-1":
			"/blog/product/zestaw-rekreacyjny-jednowiezowy-smiglak-1",
		"/lawka-prosta": "/blog/product/lawka-prosta",
		"/street-workout-sthenos-20a": "/blog/product/street-workout-sthenos-20a",
		"/street-workout-sthenos-19": "/blog/product/street-workout-sthenos-19",
		"/street-workout-sthenos-18": "/blog/product/street-workout-sthenos-18",
		"/street-workout-sthenos-17": "/blog/product/street-workout-sthenos-17",
		"/lawka-narozna-katowa": "/blog/product/lawka-narozna-katowa",
		"/lawka-narozna-lukowa": "/blog/product/lawka-narozna-lukowa",
		"/street-workout-sthenos-15a": "/blog/product/street-workout-sthenos-15a",
		"/urzadzenie-sprawnosciowe-sthenos-14": "/blog/product/urzadzenie-sprawnosciowe-sthenos-14",
		"/street-workout-sthenos-13": "/blog/product/street-workout-sthenos-13",
		"/street-workout-sthenos-12a": "/blog/product/street-workout-sthenos-12a",
		"/street-workout-sthenos-11": "/blog/product/street-workout-sthenos-11",
		"/chata-indianska": "/blog/product/chata-indianska",
		"/street-workout-sthenos-10": "/blog/product/street-workout-sthenos-10",
		"/street-workout-sthenos-9a": "/blog/product/street-workout-sthenos-9a",
		"/urzadzenie-sprawnosciowe-sthenos-8a": "/blog/product/urzadzenie-sprawnosciowe-sthenos-8a",
		"/street-workout-sthenos-7": "/blog/product/street-workout-sthenos-7",
		"/street-workout-sthenos-6": "/blog/product/street-workout-sthenos-6",
		"/street-workout-sthenos-4": "/blog/product/street-workout-sthenos-4",
		"/urzadzenie-sprawnosciowe-sthenos-3": "/blog/product/urzadzenie-sprawnosciowe-sthenos-3",
		"/urzadzenie-sprawnosciowe-sthenos-2": "/blog/product/urzadzenie-sprawnosciowe-sthenos-2",
		"/hustawka-gieta-kasia-2": "/blog/product/hustawka-gieta-kasia-2",
		"/hustawka-kuba-mini": "/blog/product/hustawka-kuba-mini",
		"/hustawka-kuba-maxi": "/blog/product/hustawka-kuba-maxi",
		"/hustawka-waga": "/blog/product/hustawka-waga",
		"/hustawka-piotr": "/blog/product/hustawka-piotr",
		"/hustawka-piotr-2": "/blog/product/hustawka-piotr-2",
		"/hustawka-jolka": "/blog/product/hustawka-jolka",
		"/hustawka-jolka-2": "/blog/product/hustawka-jolka-2",
		"/hustawka-piotr-bocianie-gniazdo": "/blog/product/hustawka-piotr-bocianie-gniazdo",
		"/hustawka-piotr-2-bocianie-gniazdo": "/blog/product/hustawka-piotr-2-bocianie-gniazdo",
		"/hustawka-jolka-bocianie-gniazdo": "/blog/product/hustawka-jolka-bocianie-gniazdo",
		"/hustawka-marek": "/blog/product/hustawka-marek",
		"/hustawka-zula": "/blog/product/hustawka-zula",
		"/hustawka-wazka-modra": "/blog/product/hustawka-wazka-modra",
		"/hustawka-wazka-motyl": "/blog/product/hustawka-wazka-motyl",
		"/hustawka-wazka-mewa": "/blog/product/hustawka-wazka-mewa",
		"/hustawka-sprezynowa-smiglo-wzor-rys-a": "/blog/product/hustawka-sprezynowa-smiglo-wzor-rys-a",
		"/hustawka-sprezynowa-smiglo-wzor-rys-max":
			"/blog/product/hustawka-sprezynowa-smiglo-wzor-rys-max",
		"/hustawka-sprezynowa-rodeo": "/blog/product/hustawka-sprezynowa-rodeo",
		"/hustawka-sprezynowa-smiglo-wzor-rodeo-max":
			"/blog/product/hustawka-sprezynowa-smiglo-wzor-rodeo-max",
		"/hustawka-sprezynowa-smiglo-wzor-rodeo-max-2":
			"/blog/product/hustawka-sprezynowa-smiglo-wzor-rodeo-max-2",
		"/hustawka-sprezynowa-kaczorek": "/blog/product/hustawka-sprezynowa-kaczorek",
		"/hustawka-sprezynowa-bmx": "/blog/product/hustawka-sprezynowa-bmx",
		"/hustawka-sprezynowa-zaba": "/blog/product/hustawka-sprezynowa-zaba",
		"/hustawka-sprezynowa-labirynt": "/blog/product/hustawka-sprezynowa-labirynt",
		"/hustawka-sprezynowa-smiglo-2": "/blog/product/hustawka-sprezynowa-smiglo-2",
		"/hustawka-sprezynowa-smiglo-wzor-platforma-batuta":
			"/blog/product/hustawka-sprezynowa-smiglo-wzor-platforma-batuta",
		"/urzadzenie-sprawnosciowe-sthenos-1": "/blog/product/urzadzenie-sprawnosciowe-sthenos-1",
		"/koszykowka-kangur": "/blog/product/koszykowka-kangur",
		"/koszykowka-foka": "/blog/product/koszykowka-foka",
		"/slupki-do-siatkowki-comes": "/blog/product/slupki-do-siatkowki-comes",
		"/bramka-do-pilki-recznej-3000-x-2000": "/blog/product/bramka-do-pilki-recznej-3000-x-2000",
		"/bramka-do-pilki-noznej-5000-x-2000": "/blog/product/bramka-do-pilki-noznej-5000-x-2000",
		"/bramka-z-koszem": "/blog/product/bramka-z-koszem",
		"/barierka-odgradzajaca-a": "/blog/product/barierka-odgradzajaca-a",
		"/barierka-odgradzajaca-b": "/blog/product/barierka-odgradzajaca-b",
		"/kosz-parkowy-6": "/blog/product/kosz-parkowy-6",
		"/plotek-strefy-bezpieczenstwa": "/blog/product/plotek-strefy-bezpieczenstwa",
		"/plotek-panelowy": "/blog/product/plotek-panelowy",
		"/stojak-rowerowy-tur": "/blog/product/stojak-rowerowy-tur",
		"/stojak-rowerowy-bobr": "/blog/product/stojak-rowerowy-bobr",
		"/stojak-rowerowy-zubr": "/blog/product/stojak-rowerowy-zubr",
		"/regulamin-placu-zabaw": "/blog/product/regulamin-placu-zabaw",
		"/trzepak-osiedlowy": "/blog/product/trzepak-osiedlowy",
		"/regulamin-placu-zabaw-ze-stojakiem-rowerowym":
			"/blog/product/regulamin-placu-zabaw-ze-stojakiem-rowerowym",
		"/kosz-parkowy-okragly-retro": "/blog/product/kosz-parkowy-okragly-retro",
		"/lawka-zeliwna-comes": "/blog/product/lawka-zeliwna-comes",
		"/lawka-stalowa-z-oparciem-jacek": "/blog/product/lawka-stalowa-z-oparciem-jacek",
		"/lawka-stalowa-junior": "/blog/product/lawka-stalowa-junior",
		"/lawka-agatka": "/blog/product/lawka-agatka",
		"/stolik-z-lawkami-szach": "/blog/product/stolik-z-lawkami-szach",
		"/stol-zeliwny-comes": "/blog/product/stol-zeliwny-comes",
		"/lawka-betonowa-kompan": "/blog/product/lawka-betonowa-kompan",
		"/stol-z-lawkami-betonowy-biesiada": "/blog/product/stol-z-lawkami-betonowy-biesiada",
		"/lawka-betonowa-elegant": "/blog/product/lawka-betonowa-elegant",
		"/lawka-betonowa-bez-oparcia-sam": "/blog/product/lawka-betonowa-bez-oparcia-sam",
		"/lawka-duo": "/blog/product/lawka-duo",
		"/lawka-betonowa-wolnostojaca": "/blog/product/lawka-betonowa-wolnostojaca",
		"/lawka-krzys": "/blog/product/lawka-krzys",
		"/kiwak-monocykl": "/blog/product/kiwak-monocykl",
		"/kiwak-animal": "/blog/product/kiwak-animal",
		"/kiwak-bicykl": "/blog/product/kiwak-bicykl",
		"/kiwak-dublo": "/blog/product/kiwak-dublo",
		"/urzadzenie-linarne-choinka": "/blog/product/urzadzenie-linarne-choinka",
		"/urzadzenie-linarne-korona": "/blog/product/urzadzenie-linarne-korona",
		"/urzadzenie-linarne-drzewko": "/blog/product/urzadzenie-linarne-drzewko",
		"/linarium-piramida": "/blog/product/linarium-piramida",
		"/urzadzenie-linarne-namiot": "/blog/product/urzadzenie-linarne-namiot",
		"/urzadzenie-linarne-dwie-sieci-z-rura": "/blog/product/urzadzenie-linarne-dwie-sieci-z-rura",
		"/system-linarny-maly-tarzan": "/blog/product/system-linarny-maly-tarzan",
		"/maly-tarzan-12-09-00": "/blog/product/maly-tarzan-12-09-00",
		"/domek-tomek": "/blog/product/domek-tomek",
		"/domek-lolek": "/blog/product/domek-lolek",
		"/domek-sklepik": "/blog/product/domek-sklepik",
		"/zestaw-sklep": "/blog/product/zestaw-sklep",
		"/zestaw-sklepy": "/blog/product/zestaw-sklepy",
		"/scianka-skalkowa-trojstronna-trzy-korony":
			"/blog/product/scianka-skalkowa-trojstronna-trzy-korony",
		"/zestaw-gimnastyczny-poligon-szesciokat":
			"/blog/product/zestaw-gimnastyczny-poligon-szesciokat",
		"/zestaw-gimnastyczny-sciezka-zdrowia": "/blog/product/zestaw-gimnastyczny-sciezka-zdrowia",
		"/tablica-do-rysowania-kreda-ala": "/blog/product/tablica-do-rysowania-kreda-ala",
		"/zestaw-lokomotywa-b": "/blog/product/zestaw-lokomotywa-b",
		"/wagonik": "/blog/product/wagonik",
		"/statek": "/blog/product/statek",
		"/urzadzenie-linarne-zagiel": "/blog/product/urzadzenie-linarne-zagiel",
		"/tunel": "/blog/product/tunel",
		"/tablica-aga": "/blog/product/tablica-aga",
		"/piaskownica-malwa-2-x-3-m": "/blog/product/piaskownica-malwa-2-x-3-m",
		"/piaskownica-malwa-bis": "/blog/product/piaskownica-malwa-bis",
		"/piaskownica-malwinka": "/blog/product/piaskownica-malwinka",
		"/zestaw-gimnastyczny-6-polowy-poligon": "/blog/product/zestaw-gimnastyczny-6-polowy-poligon",
		"/piaskownica-gucio": "/blog/product/piaskownica-gucio",
		"/piaskownica-gucio-z-zadaszeniem": "/blog/product/piaskownica-gucio-z-zadaszeniem",
		"/stolik-do-piaskownicy-b": "/blog/product/stolik-do-piaskownicy-b",
		"/stolik-do-piaskownicy-a": "/blog/product/stolik-do-piaskownicy-a",
		"/rakieta-trojstronna": "/blog/product/rakieta-trojstronna",
		"/zjezdzalnia-hipcio": "/blog/product/zjezdzalnia-hipcio",
		"/zjezdzalnia-hipcio-i": "/blog/product/zjezdzalnia-hipcio-i",
		"/zjezdzalnia-skrzat-b": "/blog/product/zjezdzalnia-skrzat-b",
		"/zjezdzalnia-duet": "/blog/product/zjezdzalnia-duet",
		"/zjezdzalnia-dino": "/blog/product/zjezdzalnia-dino",
		"/zjezdzalnia-jaga": "/blog/product/zjezdzalnia-jaga",
		"/zjezdzalnia-krasnal-1": "/blog/product/zjezdzalnia-krasnal-1",
		"/zjezdzalnia-krasnal-2": "/blog/product/zjezdzalnia-krasnal-2",
		"/zjezdzalnia-krasnal-3-slon": "/blog/product/zjezdzalnia-krasnal-3-slon",
		"/piaskownica-siedmiokropka": "/blog/product/piaskownica-siedmiokropka",
		"/zestaw-modulowy-06-61-00-slon": "/blog/product/zestaw-modulowy-06-61-00-slon",
		"/zestaw-modulowy-06-62-00-hipopotam": "/blog/product/zestaw-modulowy-06-62-00-hipopotam",
		"/zjezdzalnia-krasnal-4": "/blog/product/zjezdzalnia-krasnal-4",
		"/zestaw-rekreacyjny-julek-a": "/blog/product/zestaw-rekreacyjny-julek-a",
		"/zestaw-modulowy-06-56-00": "/blog/product/zestaw-modulowy-06-56-00",
		"/zestaw-rekreacyjny-julek-b": "/blog/product/zestaw-rekreacyjny-julek-b",
		"/karuzela-krzyzowa-jas": "/blog/product/karuzela-krzyzowa-jas",
		"/karuzela-trojramienna-jas-3": "/blog/product/karuzela-trojramienna-jas-3",
		"/karuzela-talerzowa-bak": "/blog/product/karuzela-talerzowa-bak",
		"/karuzela-trzmiel": "/blog/product/karuzela-trzmiel",
		"/karuzela-baczek": "/blog/product/karuzela-baczek",
		"/karuzela-trojramienna-osa": "/blog/product/karuzela-trojramienna-osa",
		"/karuzela-jas-2": "/blog/product/karuzela-jas-2",
		"/karuzela-swing": "/blog/product/karuzela-swing",
		"/karuzela-kolowiec": "/blog/product/karuzela-kolowiec",
		"/karuzela-alfa": "/blog/product/karuzela-alfa",
		"/przeplotnia-smok": "/blog/product/przeplotnia-smok",
		"/przeplotnia-rakieta-a": "/blog/product/przeplotnia-rakieta-a",
		"/przeplotnia-hangar": "/blog/product/przeplotnia-hangar",
		"/przeplotnia-hangar-linowy": "/blog/product/przeplotnia-hangar-linowy",
		"/przeplotnia-drazek-ukosny": "/blog/product/przeplotnia-drazek-ukosny",
		"/przeplotnia-drazki": "/blog/product/przeplotnia-drazki",
		"/przeplotnia-bajka": "/blog/product/przeplotnia-bajka",
		"/sciezka-zdrowia-mlynek": "/blog/product/sciezka-zdrowia-mlynek",
		"/sciezka-zdrowia-zolw-ii": "/blog/product/sciezka-zdrowia-zolw-ii",
		"/przeplotnia-rakieta-b": "/blog/product/przeplotnia-rakieta-b",
		"/przeplotnia-baza-kosmiczna": "/blog/product/przeplotnia-baza-kosmiczna",
		"/sciezka-zdrowia-zolw-i": "/blog/product/sciezka-zdrowia-zolw-i",
		"/zestaw-06-51-152": "/blog/product/zestaw-06-51-152",
		"/stacja-ladujaca": "/blog/product/stacja-ladujaca",
		"/zestaw-modulowy-06-59-135": "/blog/product/zestaw-modulowy-06-59-135",
		"/lawka-witek": "/blog/product/lawka-witek",
		"/tablica-informacyjna-2": "/blog/product/tablica-informacyjna-2",
		"/zestaw-06-59-107": "/blog/product/zestaw-06-59-107",
		"/zestaw-06-59-104": "/blog/product/zestaw-06-59-104",
		"/zestaw-06-59-90": "/blog/product/zestaw-06-59-90",
		"/radiowoz": "/blog/product/radiowoz",
		"/zestaw-06-59-91": "/blog/product/zestaw-06-59-91",
		"/helikopter-na-sprezynach": "/blog/product/helikopter-na-sprezynach",
		"/zestaw-06-59-124": "/blog/product/zestaw-06-59-124",
		"/zestaw-06-59-122": "/blog/product/zestaw-06-59-122",
		"/straz-pozarna": "/blog/product/straz-pozarna",
		"/plotek-do-przeskokow-regulowany": "/blog/product/plotek-do-przeskokow-regulowany",
		"/hustawka-wagowa-modra-2": "/blog/product/hustawka-wagowa-modra-2",
		"/kosz-na-psie-odchody": "/blog/product/kosz-na-psie-odchody",
		"/sciezka-sensoryczna": "/blog/product/sciezka-sensoryczna",
		"/zestaw-06-59-118": "/blog/product/zestaw-06-59-118",
		"/zestaw-06-59-88": "/blog/product/zestaw-06-59-88",
		"/hustawka-wagowa-mewa-ii": "/blog/product/hustawka-wagowa-mewa-ii",
		"/zestaw-dla-psow-1": "/blog/product/zestaw-dla-psow-1",
		"/tunel-do-przechodzenia": "/blog/product/tunel-do-przechodzenia",
		"/zestaw-06-59-97": "/blog/product/zestaw-06-59-97",
		"/plotki-do-przeskokow-2-szt": "/blog/product/plotki-do-przeskokow-2-szt",
		"/zestaw-06-59-111": "/blog/product/zestaw-06-59-111",
		"/zestaw-06-59-117": "/blog/product/zestaw-06-59-117",
		"/zestaw-06-59-130": "/blog/product/zestaw-06-59-130",
		"/zestaw-06-59-87": "/blog/product/zestaw-06-59-87",
		"/zestaw-06-59-99": "/blog/product/zestaw-06-59-99",
		"/fabryka-piasku-ii": "/blog/product/fabryka-piasku-ii",
		"/ambulans": "/blog/product/ambulans",
		"/zestaw-06-59-121": "/blog/product/zestaw-06-59-121",
		"/poprzeczki-do-przejscia": "/blog/product/poprzeczki-do-przejscia",
		"/street-workout-15-96-00": "/blog/product/street-workout-15-96-00",
		"/zestaw-06-59-112": "/blog/product/zestaw-06-59-112",
		"/06-59-119": "/blog/product/06-59-119",
		"/trap-2": "/blog/product/trap-2",
		"/zestaw-dla-psow-2": "/blog/product/zestaw-dla-psow-2",
		"/zestaw-06-51-159": "/blog/product/zestaw-06-51-159",
		"/zestaw-06-51-165": "/blog/product/zestaw-06-51-165",
		"/hustawka-jolka-2-ab1": "/blog/product/hustawka-jolka-2-ab1",
		"/piaskownica-malwa-3-x-3-m": "/blog/product/piaskownica-malwa-3-x-3-m",
		"/slupek-psia-toaleta": "/blog/product/slupek-psia-toaleta",
		"/street-workout-sthenos-9b": "/blog/product/street-workout-sthenos-9b",
		"/podest-z-kladkami": "/blog/product/podest-z-kladkami",
		"/hustawka-sprezynowa-sowa-2": "/blog/product/hustawka-sprezynowa-sowa-2",
		"/wiata": "/blog/product/wiata",
		"/zestawy-06-59-18": "/blog/product/zestawy-06-59-18",
		"/zestaw-modulowy-06-51-250": "/blog/product/zestaw-modulowy-06-51-250",
		"/piaskownica-malwa-3-x-6-m-lesna-polana":
			"/blog/product/piaskownica-malwa-3-x-6-m-lesna-polana",
		"/street-workout-15-79-00": "/blog/product/street-workout-15-79-00",
		"/kosz-do-segregacji": "/blog/product/kosz-do-segregacji",
		"/street-workout-15-91-00": "/blog/product/street-workout-15-91-00",
		"/zestaw-06-51-200": "/blog/product/zestaw-06-51-200",
		"/lawka-junior-b": "/blog/product/lawka-junior-b",
		"/karuzela-integracyjna": "/blog/product/karuzela-integracyjna",
		"/piaskownica-malwinka-25-x-25-m-wodny-swiat":
			"/blog/product/piaskownica-malwinka-25-x-25-m-wodny-swiat",
		"/hustawka-wagowa-skosna": "/blog/product/hustawka-wagowa-skosna",
		"/plotek-strefy-bezpieczenstwa-furtka": "/blog/product/plotek-strefy-bezpieczenstwa-furtka",
		"/street-workout-sthenos-8b": "/blog/product/street-workout-sthenos-8b",
		"/siec-p2": "/blog/product/siec-p2",
		"/malwinka-25-x-25-m": "/blog/product/malwinka-25-x-25-m",
		"/zestaw-modulowy-06-51-223-samolot": "/blog/product/zestaw-modulowy-06-51-223-samolot",
		"/zestaw-06-51-244": "/blog/product/zestaw-06-51-244",
		"/hustawka-sprezynowa-okret-2": "/blog/product/hustawka-sprezynowa-okret-2",
		"/zestaw-06-48-10": "/blog/product/zestaw-06-48-10",
		"/zestaw-06-51-120": "/blog/product/zestaw-06-51-120",
		"/piaskownica-gucio-potrojna": "/blog/product/piaskownica-gucio-potrojna",
		"/scianka-wspinaczkowa-skalkowa-2": "/blog/product/scianka-wspinaczkowa-skalkowa-2",
		"/zestaw-06-52-16": "/blog/product/zestaw-06-52-16",
		"/hustawka-sprezynowa-owieczka-2": "/blog/product/hustawka-sprezynowa-owieczka-2",
		"/pojazd-dostawczy": "/blog/product/pojazd-dostawczy",
		"/stojak-rowerowy-bobr-10-stanowiskowy": "/blog/product/stojak-rowerowy-bobr-10-stanowiskowy",
		"/hustawka-sprezynowa-jeep-2": "/blog/product/hustawka-sprezynowa-jeep-2",
		"/wagonik-autko": "/blog/product/wagonik-autko",
		"/hustawka-sprezynowa-latajacy-spodek-2": "/blog/product/hustawka-sprezynowa-latajacy-spodek-2",
		"/zestaw-modulowy-06-59-42": "/blog/product/zestaw-modulowy-06-59-42",
		"/piaskownica-malwa-3-x-6-m": "/blog/product/piaskownica-malwa-3-x-6-m",
		"/hustawka-systemowa-pojedyncza": "/blog/product/hustawka-systemowa-pojedyncza",
		"/stolik-z-lawkami-szach-7-15-lat": "/blog/product/stolik-z-lawkami-szach-7-15-lat",
		"/piaskownica-malwa-4-x-5-m": "/blog/product/piaskownica-malwa-4-x-5-m",
		"/karuzela-biegowa": "/blog/product/karuzela-biegowa",
		"/maly-tarzan-12-10-09": "/blog/product/maly-tarzan-12-10-09",
		"/sprezynowka-potrojna-konik": "/blog/product/sprezynowka-potrojna-konik",
		"/kiwak-dwukierunkowy": "/blog/product/kiwak-dwukierunkowy",
		"/zestaw-modulowy-06-51-248": "/blog/product/zestaw-modulowy-06-51-248",
		"/zestaw-modulowy-06-51-232": "/blog/product/zestaw-modulowy-06-51-232",
		"/zestaw-06-51-205": "/blog/product/zestaw-06-51-205",
		"/piaskownica-malwa-4-x-4-m": "/blog/product/piaskownica-malwa-4-x-4-m",
		"/street-workout-sthenos-52": "/blog/product/street-workout-sthenos-52",
		"/zestaw-06-48-55": "/blog/product/zestaw-06-48-55",
		"/pajeczyna": "/blog/product/pajeczyna",
		"/piaskownica-zamykana": "/blog/product/piaskownica-zamykana",
		"/hustawka-kasia-2-ab1": "/blog/product/hustawka-kasia-2-ab1",
		"/hustawka-wagowa-motyl-2": "/blog/product/hustawka-wagowa-motyl-2",
		"/street-workout-sthenos-20b": "/blog/product/street-workout-sthenos-20b",
		"/lawka-systemowa": "/blog/product/lawka-systemowa",
		"/lawka-julia-grzybek": "/blog/product/lawka-julia-grzybek",
		"/zestaw-06-51-194": "/blog/product/zestaw-06-51-194",
		"/zestaw-06-51-146": "/blog/product/zestaw-06-51-146",
		"/zestaw-modulowy-06-51-247": "/blog/product/zestaw-modulowy-06-51-247",
		"/hustawka-sprezynowa-nosorozec": "/blog/product/hustawka-sprezynowa-nosorozec",
		"/lawka-zwierzak": "/blog/product/lawka-zwierzak",
		"/lawka-zwierzak-2": "/blog/product/lawka-zwierzak-2",
		"/hustawka-sprezynowa-motyl": "/blog/product/hustawka-sprezynowa-motyl",
		"/zestaw-modulowy-06-51-239": "/blog/product/zestaw-modulowy-06-51-239",
		"/przeplotnia-bajka-motyl": "/blog/product/przeplotnia-bajka-motyl",
		"/zestaw-06-51-160": "/blog/product/zestaw-06-51-160",
		"/kamien-papier-nozyce": "/blog/product/kamien-papier-nozyce",
		"/lawka-julia-2": "/blog/product/lawka-julia-2",
		"/zestaw-06-51-240": "/blog/product/zestaw-06-51-240",
		"/lawka-ola": "/blog/product/lawka-ola",
		"/street-workout-15-115-00": "/blog/product/street-workout-15-115-00",
		"/zestaw-modulowy-06-51-238": "/blog/product/zestaw-modulowy-06-51-238",
		"/lawka-ula": "/blog/product/lawka-ula",
		"/lawka-stas": "/blog/product/lawka-stas",
		"/zestaw-modulowy-06-62-00-lew": "/blog/product/zestaw-modulowy-06-62-00-lew",
		"/zestaw-modulowy-06-51-85": "/blog/product/zestaw-modulowy-06-51-85",
		"/zestaw-statek-06-51-259": "/blog/product/zestaw-statek-06-51-259",
		"/zestaw-modulowy-06-51-127": "/blog/product/zestaw-modulowy-06-51-127",
		"/zestaw-modulowy-06-51-112": "/blog/product/zestaw-modulowy-06-51-112",
		"/street-workout-sthenos-51": "/blog/product/street-workout-sthenos-51",
		"/zestaw-modulowy-06-51-110": "/blog/product/zestaw-modulowy-06-51-110",
		"/zestaw-modulowy-06-51-236": "/blog/product/zestaw-modulowy-06-51-236",
		"/zestaw-modulowy-06-61-02-kon": "/blog/product/zestaw-modulowy-06-61-02-kon",
		"/zestaw-06-51-258": "/blog/product/zestaw-06-51-258",
		"/zestaw-modulowy-06-62-00-nosorozec": "/blog/product/zestaw-modulowy-06-62-00-nosorozec",
		"/hustawka-jolka-3-ag": "/blog/product/hustawka-jolka-3-ag",
		"/zestaw-modulowy-06-51-91": "/blog/product/zestaw-modulowy-06-51-91",
		"/regulamin-placu-zabaw-2": "/blog/product/regulamin-placu-zabaw-2",
		"/zestaw-modulowy-06-51-82": "/blog/product/zestaw-modulowy-06-51-82",
		"/hustawka-jolka-4-ab1g": "/blog/product/hustawka-jolka-4-ab1g",
		"/hustawka-piotr-3-b1b1g": "/blog/product/hustawka-piotr-3-b1b1g",
		"/zestaw-modulowy-06-51-237": "/blog/product/zestaw-modulowy-06-51-237",
		"/tunel-dlugi": "/blog/product/tunel-dlugi",
		"/zestaw-modulowy-06-51-249": "/blog/product/zestaw-modulowy-06-51-249",
		"/stojak-rowerowy-bobr-3-stanowiskowy": "/blog/product/stojak-rowerowy-bobr-3-stanowiskowy",
		"/zestaw-modulowy-06-62-00-wielblad": "/blog/product/zestaw-modulowy-06-62-00-wielblad",
		"/stojak-rowerowy-bobr-5-stanowiskowy": "/blog/product/stojak-rowerowy-bobr-5-stanowiskowy",
		"/stojak-rowerowy-tur-3": "/blog/product/stojak-rowerowy-tur-3",
		"/fabryka-piasku": "/blog/product/fabryka-piasku",
		"/tor-szkoleniowy-dla-psow": "/blog/product/tor-szkoleniowy-dla-psow",
		"/hustawka-systemowa-podwojna": "/blog/product/hustawka-systemowa-podwojna",
		"/plotek-strefy-bezpieczenstwa-przeslo-ii":
			"/blog/product/plotek-strefy-bezpieczenstwa-przeslo-ii",
		"/stojak-rowerowy-bobr-4-stanowiskowy": "/blog/product/stojak-rowerowy-bobr-4-stanowiskowy",
		"/zestaw-modulowy-06-59-100": "/blog/product/zestaw-modulowy-06-59-100",
		"/stojak-rowerowy-bobr-6-stanowiskowy": "/blog/product/stojak-rowerowy-bobr-6-stanowiskowy",
		"/stojak-rowerowy-bobr-2-stanowiskowy": "/blog/product/stojak-rowerowy-bobr-2-stanowiskowy",
		"/zestaw-modulowy-06-59-75": "/blog/product/zestaw-modulowy-06-59-75",
		"/lawka-junior-a": "/blog/product/lawka-junior-a",
		"/hustawka-sprezynowa-kaczka": "/blog/product/hustawka-sprezynowa-kaczka",
		"/zestaw-modulowy-06-51-246-pianino": "/blog/product/zestaw-modulowy-06-51-246-pianino",
		"/podciagacz-dla-niepelnosprawnych": "/blog/product/podciagacz-dla-niepelnosprawnych",
		"/street-workout-sthenos-15b": "/blog/product/street-workout-sthenos-15b",
		"/stojak-rowerowy-modern-2": "/blog/product/stojak-rowerowy-modern-2",
		"/piaskownica-edukacyjna": "/blog/product/piaskownica-edukacyjna",
		"/street-workout-sthenos-16": "/blog/product/street-workout-sthenos-16",
		"/lawka-tola": "/blog/product/lawka-tola",
		"/street-workout-sthenos-53": "/blog/product/street-workout-sthenos-53",
		"/street-workout-sthenos-12b": "/blog/product/street-workout-sthenos-12b",
		"/siec-p1": "/blog/product/siec-p1",
		"/street-workout-15-60-00": "/blog/product/street-workout-15-60-00",
		"/street-workout-sthenos-12c-kopia": "/blog/product/street-workout-sthenos-12c-kopia",
		"/lesna-chatka": "/blog/product/lesna-chatka",
		"/zestaw-modulowy-06-51-226-samolot": "/blog/product/zestaw-modulowy-06-51-226-samolot",
		"/tablica-sklepik": "/blog/product/tablica-sklepik",
		"/street-workout-sthenos-58": "/blog/product/street-workout-sthenos-58",
		"/scianka-gimnastyczna-b": "/blog/product/scianka-gimnastyczna-b",
		"/tablica-labirynt": "/blog/product/tablica-labirynt",
		"/street-workout-15-86-00": "/blog/product/street-workout-15-86-00",
		"/street-workout-sthenos-50": "/blog/product/street-workout-sthenos-50",
		"/slalom-dla-psow": "/blog/product/slalom-dla-psow",
		"/stol-z-lawkami-senior-2": "/blog/product/stol-z-lawkami-senior-2",
		"/krzeslo": "/blog/product/krzeslo",
		"/stolik-do-piaskownicy-c": "/blog/product/stolik-do-piaskownicy-c",
		"/street-workout-15-80-00": "/blog/product/street-workout-15-80-00",
		"/plotek-panelowy-przeslo": "/blog/product/plotek-panelowy-przeslo",
		"/street-workout-15-89-00": "/blog/product/street-workout-15-89-00",
		"/street-workout-15-85-00": "/blog/product/street-workout-15-85-00",
		"/stojak-rowerowy-tur-2": "/blog/product/stojak-rowerowy-tur-2",
		"/zestaw-modulowy-06-51-245-syntezator": "/blog/product/zestaw-modulowy-06-51-245-syntezator",
		"/street-workout-sthenos-54": "/blog/product/street-workout-sthenos-54",
		"/trzepak-osiedlowy-3": "/blog/product/trzepak-osiedlowy-3",
		"/piaskownica-mini": "/blog/product/piaskownica-mini",
		"/tablica-autko": "/blog/product/tablica-autko",
		"/kosz-parkowy-6-ii": "/blog/product/kosz-parkowy-6-ii",
		"/karuzela-trzmiel-2": "/blog/product/karuzela-trzmiel-2",
		"/zjezdzalnia-skrzat-a": "/blog/product/zjezdzalnia-skrzat-a",
		"/trzepak-osiedlowy-2": "/blog/product/trzepak-osiedlowy-2",
		"/plotek-strefy-bezpieczenstwa-furtka-ii":
			"/blog/product/plotek-strefy-bezpieczenstwa-furtka-ii",
		"/regulamin-retro-2": "/blog/product/regulamin-retro-2",
		"/hustawka-sprezynowa-mis": "/blog/product/hustawka-sprezynowa-mis",
		"/plac-zabaw-w-radomiu": "/blog/realizacje/plac-zabaw-w-radomiu",
		"/piaskownica-gucio-podwojna": "/blog/product/piaskownica-gucio-podwojna",
		"/plac-zabaw-w-sosnowcu-przy-ulicy-norwida":
			"/blog/realizacje/plac-zabaw-w-sosnowcu-przy-ulicy-norwida",
		"/plac-zabaw-kozienice": "/blog/realizacje/plac-zabaw-kozienice",
		"/piaskownica-gucio-z-zadaszeniem-lesna-polana":
			"/blog/product/piaskownica-gucio-z-zadaszeniem-lesna-polana",
		"/silownia-plenerowa-w-radomiu": "/blog/realizacje/silownia-plenerowa-w-radomiu",
		"/sensoryczne-panele-muzyczne": "/blog/realizacje/sensoryczne-panele-muzyczne",
		"/plac-zabaw-w-warszawie-przy-zespole-szkol-specjalnych-nr-91":
			"/blog/realizacje/plac-zabaw-w-warszawie-przy-zespole-szkol-specjalnych-nr-91",
		"/plac-zabaw-i-silownia-ul-cedlera-w-dabrowie-gorniczej":
			"/blog/realizacje/plac-zabaw-i-silownia-ul-cedlera-w-dabrowie-gorniczej",
		"/plac-zabaw-w-sosnowcu-przy-ul-lwowskiej":
			"/blog/realizacje/plac-zabaw-w-sosnowcu-przy-ul-lwowskiej",
		"/plac-zabaw-w-bielsku-bialej-przy-ul-lagodnej-i-siewnej":
			"/blog/realizacje/plac-zabaw-w-bielsku-bialej-przy-ul-lagodnej-i-siewnej",
		"/plac-zabaw-w-bielsku-bialej-na-osiedlu-piastowskim-przy-ul-sobieskiego-103":
			"/blog/realizacje/plac-zabaw-w-bielsku-bialej-na-osiedlu-piastowskim-przy-ul-sobieskiego-103",
		"/plac-zabaw-w-warszawie-przy-szkole-podstawowej-nr-177":
			"/blog/realizacje/plac-zabaw-w-warszawie-przy-szkole-podstawowej-nr-177",
		"/plac-zabaw-w-bielsku-bialej-przy-ul-zlotych-klosow":
			"/blog/realizacje/plac-zabaw-w-bielsku-bialej-przy-ul-zlotych-klosow",
		"/place-zabaw-i-silownia-plac-papieski-sosnowiec":
			"/blog/realizacje/place-zabaw-i-silownia-plac-papieski-sosnowiec",
		"/plac-zabaw-przy-miejskim-zespole-szkol-w-bilgoraju":
			"/blog/realizacje/plac-zabaw-przy-miejskim-zespole-szkol-w-bilgoraju",
		"/plac-zabaw-w-jastrzebiu-zdroju-na-ulicy-pomorskiej":
			"/blog/realizacje/plac-zabaw-w-jastrzebiu-zdroju-na-ulicy-pomorskiej",
		"/plac-zabaw-i-silownia-ul-krakowska-w-sosnowcu":
			"/blog/realizacje/plac-zabaw-i-silownia-ul-krakowska-w-sosnowcu",
		"/plac-zabaw-w-konskich": "/blog/realizacje/plac-zabaw-w-konskich",
		"/silownia-plenerowa-ul-gorna-w-dabrowie-gorniczej":
			"/blog/realizacje/silownia-plenerowa-ul-gorna-w-dabrowie-gorniczej",
		"/plac-zabaw-w-woli-rebkowskiej": "/blog/realizacje/plac-zabaw-w-woli-rebkowskiej",
		"/plac-zabaw-przy-publicznym-przedszkolu-samorzadowym-w-lipsku":
			"/blog/realizacje/plac-zabaw-przy-publicznym-przedszkolu-samorzadowym-w-lipsku",
		"/dziki-zachod-tematyczny-plac-zabaw-w-opolu":
			"/blog/realizacje/dziki-zachod-tematyczny-plac-zabaw-w-opolu",
		"/plac-zabaw-w-czarnym-borze": "/blog/realizacje/plac-zabaw-w-czarnym-borze",
		"/plac-zabaw-przy-zespole-placowek-oswiatowych-w-krasocinie":
			"/blog/realizacje/plac-zabaw-przy-zespole-placowek-oswiatowych-w-krasocinie",
		"/zestaw-street-workout": "/blog/realizacje/zestaw-street-workout",
		"/plac-zabaw-comes-przy-ulicy-slowiczej-w-toruniu":
			"/blog/realizacje/plac-zabaw-comes-przy-ulicy-slowiczej-w-toruniu",
		"/plac-zabaw-w-jastrzebiu-zdroju-na-ulicy-jasnej":
			"/blog/realizacje/plac-zabaw-w-jastrzebiu-zdroju-na-ulicy-jasnej",
		"/indianski-plac-zabaw": "/blog/realizacje/indianski-plac-zabaw",
		"/plac-zabaw-starachowice": "/blog/realizacje/plac-zabaw-starachowice",
		"/silownia-plenerowa-w-podlesicach": "/blog/realizacje/silownia-plenerowa-w-podlesicach",
		"/silownia-plenerowa-sm-zagorze": "/blog/realizacje/silownia-plenerowa-sm-zagorze",
		"/wybieg-dla-psow-w-kielcach": "/blog/realizacje/wybieg-dla-psow-w-kielcach",
		"/plac-zabaw-w-wyszkowie-2": "/blog/realizacje/plac-zabaw-w-wyszkowie-2",
		"/plac-zabaw-przy-ul-legionow-w-sosnowcu":
			"/blog/realizacje/plac-zabaw-przy-ul-legionow-w-sosnowcu",
		"/plac-zabaw-i-silownia-w-sosnowcu": "/blog/realizacje/plac-zabaw-i-silownia-w-sosnowcu",
		"/zamkowy-plac-zabaw": "/blog/realizacje/zamkowy-plac-zabaw",
		"/tematyczny-plac-zabaw-w-radomiu": "/blog/realizacje/tematyczny-plac-zabaw-w-radomiu",
		"/nowy-zamek-w-olsztynie": "/blog/realizacje/nowy-zamek-w-olsztynie",
		"/ogrodek-jordanowski-w-radomiu": "/blog/realizacje/ogrodek-jordanowski-w-radomiu",
		"/plac-zabaw-bierutow": "/blog/realizacje/plac-zabaw-bierutow",
		"/street-workout-zestaw-treningowy": "/blog/realizacje/street-workout-zestaw-treningowy",
		"/plac-zabaw-w-wyszkowie": "/blog/realizacje/plac-zabaw-w-wyszkowie",
		"/plac-zabaw-w-sannikach": "/blog/realizacje/plac-zabaw-w-sannikach"
	}
})
